# Site settings
title: "Animesh Rawat Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_name:                    "Animesh Rawat"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "Animeshrwt77@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "7906194157"
resume_contact_address:         "Clement Town,Dehradun"

#resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
#resume_section_experience:      no
resume_section_education:       yes
#resume_section_projects:        no
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nissu99" 
  resume_twitter_url:           "https://x.com/Animesh16667188"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
